### ISSUE TITLE
flexible config.yaml

### ISSUE THREAD

**Issue by DimaMolod** [KosinskiLab/AlphaPulldownSnakemake#11]
At the moment, it's impossible to run this pipeline with multimeric templates because the flags for rule_create_features and rule_structure_inference are hardcoded in Snakefile. 
It would be great if one could add any flag from either create_individual_features.py or run_structure_prediction.py into config.yaml to be used with snakemake. For that, the dictionaries of all flags from both scripts should be available in snakefile.

**Comment by maurerv** [comment]
Feel free to check out 7edc828e5f178aa4600c6509d8f3686337adaa8f on the expose_cliparams branch
