### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by salomonssonj** [KosinskiLab/AlphaPulldownSnakemake#16]
Hi,

When I try to run this snakemake pipeline I got this error message:

KeyError in file https://raw.githubusercontent.com/KosinskiLab/AlphaPulldownSnakemake/main/workflow/Snakefile, line 291:
'compute_stats_arguments'
  File "/home/salomonssonj/AlphaPulldownSnakemake/workflow/Snakefile", line 19, in <module>
  File "https://raw.githubusercontent.com/KosinskiLab/AlphaPulldownSnakemake/main/workflow/Snakefile", line 291, in <module>

Is it possible to fix?

Kindly,
Johannes

**Comment by salomonssonj** [comment]
Sorry, I saw that you made some changes. After updating my config.yaml file it now seem to work.

**Comment by maurerv** [comment]
Hi Johannes,

thanks for testing the pipeline and providing your feedback :)

I am glad your issue has been solved. For reference, this issue arose because snakedeploy would not honor the pipeline tag and instead use the latest snakefile in main.

Best,
Valentin
